/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FinestraFiCompra.java
 *
 * Created on 09/11/2009, 10:26:31
 */

package tpv;

/**
 *
 * @author joan
 */
public class FinestraFiCompra extends javax.swing.JFrame {

    private Register tpv;
    /** Creates new form FinestraFiCompra */
    public FinestraFiCompra() {
        initComponents();
    }
    public FinestraFiCompra(Register unTpv) {
        tpv=unTpv;
        initComponents();
        String p=(tpv.getSale().getPay().getAmount())+"";
        textPagament.setText(p);
        String c=(tpv.getSale().getCanvi())+"";
        textCanvi.setText(c);
        String t=(tpv.getSale().getTotal())+"";
        textTotal.setText(t);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textPagament = new javax.swing.JTextField();
        textCanvi = new javax.swing.JTextField();
        BtnFinalitzarCompra = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        textTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Canvi");

        jLabel1.setText("Pagament:");

        jLabel2.setText("Canvi:");

        textPagament.setEditable(false);

        textCanvi.setEditable(false);

        BtnFinalitzarCompra.setText("OK");
        BtnFinalitzarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFinalitzarCompraActionPerformed(evt);
            }
        });

        jLabel3.setText("TOTAL:");

        textTotal.setEditable(false);

        jLabel4.setText("Utilitza 'OK' per donar per finalitzat el pagament");

        jLabel5.setText("i tornar a la pantalla de iniciar compra.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textTotal)
                            .addComponent(BtnFinalitzarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textPagament)
                            .addComponent(textCanvi, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)))
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPagament, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textCanvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtnFinalitzarCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnFinalitzarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFinalitzarCompraActionPerformed
        
        tpv.finalitzaVenda();
        dispose();
        setVisible(false);
    }//GEN-LAST:event_BtnFinalitzarCompraActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinestraFiCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnFinalitzarCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField textCanvi;
    private javax.swing.JTextField textPagament;
    private javax.swing.JTextField textTotal;
    // End of variables declaration//GEN-END:variables

}
