/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FinestraIniciarTPV.java
 *
 * Created on 09/11/2009, 01:44:55
 */

package tpv;

/**
 *
 * @author joan
 */
public class FinestraIniciarTPV extends javax.swing.JFrame {

    private Store botiga;
    /** Creates new form FinestraIniciarTPV */
    public FinestraIniciarTPV() {
        initComponents();
    }
    public FinestraIniciarTPV(Store unaBotiga) {
        botiga=unaBotiga;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LDescripcio = new javax.swing.JLabel();
        LIdTreballador = new javax.swing.JLabel();
        LIdTPV = new javax.swing.JLabel();
        textIDTreballador = new javax.swing.JTextField();
        textIDTPV = new javax.swing.JTextField();
        BtnIniciarVenda = new javax.swing.JButton();
        LConsell = new javax.swing.JLabel();
        BtnTancarFinestra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Venda");

        LDescripcio.setText("Introdueix el Treballador i TPV per Iniciar una venda:  ");

        LIdTreballador.setText("idTreballador:");

        LIdTPV.setText("idTPV:");

        BtnIniciarVenda.setText("Iniciar Venda");
        BtnIniciarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIniciarVendaActionPerformed(evt);
            }
        });

        LConsell.setText("*Recorda que idTreballador i idTPV nomes accepten numeros");

        BtnTancarFinestra.setText("Tancar");
        BtnTancarFinestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTancarFinestraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(LDescripcio))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LIdTPV)
                            .addComponent(LIdTreballador))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textIDTPV)
                            .addComponent(textIDTreballador, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(BtnIniciarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnTancarFinestra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(LConsell)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(LDescripcio)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LIdTreballador)
                    .addComponent(textIDTreballador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LIdTPV)
                    .addComponent(textIDTPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtnIniciarVenda)
                .addGap(4, 4, 4)
                .addComponent(BtnTancarFinestra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LConsell)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIniciarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIniciarVendaActionPerformed
      
        int idT=Integer.parseInt(textIDTreballador.getText());
        int idR=Integer.parseInt(textIDTPV.getText());

        Cashier treballador = new Cashier(idT);
        if(botiga.getRegister(idR)==null)
        {
            Register tpv = new Register(idR, treballador, botiga);
            botiga.setRegister(tpv);
        }
        Register tpv = botiga.getRegister(idR);
        tpv.setCashier(treballador);
        tpv.crearNovaVenda();
        FinestraAfegirProductesATicket f3 = new FinestraAfegirProductesATicket(tpv);
        f3.show();
    }//GEN-LAST:event_BtnIniciarVendaActionPerformed

    private void BtnTancarFinestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTancarFinestraActionPerformed
        
        dispose();
        setVisible(false);
    }//GEN-LAST:event_BtnTancarFinestraActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinestraIniciarTPV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIniciarVenda;
    private javax.swing.JButton BtnTancarFinestra;
    private javax.swing.JLabel LConsell;
    private javax.swing.JLabel LDescripcio;
    private javax.swing.JLabel LIdTPV;
    private javax.swing.JLabel LIdTreballador;
    private javax.swing.JTextField textIDTPV;
    private javax.swing.JTextField textIDTreballador;
    // End of variables declaration//GEN-END:variables

}
