/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Finestra4.java
 *
 * Created on 09/11/2009, 09:10:03
 */

package tpv;

/**
 *
 * @author joan
 */
import java.util.LinkedHashMap;
import java.util.Collection;
import java.util.Iterator;
public class Finestra4 extends javax.swing.JFrame {

    private Register tpv;
    /** Creates new form Finestra4 */
    public Finestra4() {
        initComponents();
    }
    public Finestra4(Register unTpv) {
        tpv=unTpv;
        initComponents();
        LinkedHashMap lines=tpv.getSale().getLines();
        Collection col = lines.values();
        Iterator cIt=col.iterator();
        while(cIt.hasNext())
        {
            SalesLineItem line=(SalesLineItem)cIt.next();
            textVenda.append((line.getItem().getDescription().getDescription())+"\t\t"+(line.getQuantity())+"\t"+(line.getItem().getDescription().getPrice())+"\n");
        }
        int t=tpv.getSale().getTotal();
        textVenda.append("\nTOTAL:\t\t\t"+t);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textVenda = new javax.swing.JTextArea();
        textPagament = new javax.swing.JTextField();
        LabelPayment = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        LabelProducte = new javax.swing.JLabel();
        LabelQuantitat = new javax.swing.JLabel();
        LabelPrice = new javax.swing.JLabel();
        LabelInt = new javax.swing.JLabel();
        LabelIntr1 = new javax.swing.JLabel();
        LabelInstr2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textVenda.setColumns(20);
        textVenda.setEditable(false);
        textVenda.setRows(5);
        textVenda.setMinimumSize(new java.awt.Dimension(0, 1));
        jScrollPane1.setViewportView(textVenda);

        LabelPayment.setText("Pagament:");

        jButton1.setText("Pagar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        LabelProducte.setText("Producte");

        LabelQuantitat.setText("Quantitat");

        LabelPrice.setText("Preu unitat");

        LabelInt.setText("* int");

        LabelIntr1.setText("Introdueix al cap 'Pagament' la quantitat pagada.");

        LabelInstr2.setText("Utilitza 'Pagar'  per relaitzar el pagament.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelInstr2)
                    .addComponent(LabelIntr1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelPayment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textPagament, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelInt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelProducte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelQuantitat)
                        .addGap(18, 18, 18)
                        .addComponent(LabelPrice)
                        .addGap(28, 28, 28))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelProducte)
                    .addComponent(LabelPrice)
                    .addComponent(LabelQuantitat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelIntr1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelInstr2)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPayment)
                    .addComponent(textPagament, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelInt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int p = Integer.parseInt(textPagament.getText());
        if(p<tpv.getSale().getTotal())
        {
            ErrPagament er = new ErrPagament(this,true);
            er.show();
        }else
        {
            tpv.ferPagament(p);
            Finestra5 f5=new Finestra5(tpv);
            f5.show();
            dispose();
            setVisible(false);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finestra4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelInstr2;
    private javax.swing.JLabel LabelInt;
    private javax.swing.JLabel LabelIntr1;
    private javax.swing.JLabel LabelPayment;
    private javax.swing.JLabel LabelPrice;
    private javax.swing.JLabel LabelProducte;
    private javax.swing.JLabel LabelQuantitat;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textPagament;
    private javax.swing.JTextArea textVenda;
    // End of variables declaration//GEN-END:variables

}
