/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Finestra1.java
 *
 * Created on 09/11/2009, 01:40:16
 */

package tpv;

import java.util.Collection;
import java.util.Iterator;

/**
 *
 * @author joan
 */
public class Finestra1 extends javax.swing.JFrame {

    private Store botiga;
    private Catalog cataleg;
    private Ledger llibre;
    /** Creates new form Finestra1 */
    public Finestra1() {
        initComponents();
    }
    public Finestra1(Catalog unCataleg, Ledger unLlibre) {
        cataleg=unCataleg;
        llibre=unLlibre;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textNom = new javax.swing.JTextField();
        textAddress = new javax.swing.JTextField();
        LNom = new javax.swing.JLabel();
        LAdreça = new javax.swing.JLabel();
        LDescripcio = new javax.swing.JLabel();
        botoOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entrar botiga");

        textAddress.setName("textAddress"); // NOI18N

        LNom.setText("Nom:");

        LAdreça.setText("Adreça:");

        LDescripcio.setText("Introdueix les dades de la botiga:");

        botoOK.setText("OK");
        botoOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LDescripcio)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LNom)
                            .addComponent(LAdreça))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textAddress)
                            .addComponent(textNom, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .addComponent(botoOK, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LDescripcio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNom)
                    .addComponent(textNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LAdreça)
                    .addComponent(textAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botoOK)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoOKActionPerformed
        // TODO add your handling code here:
        
        botiga=new Store(textNom.getText(), textAddress.getText(),cataleg, llibre);
        Collection col = cataleg.getList().values();
        Iterator cIt=col.iterator();
        while(cIt.hasNext())
        {
            Item unItem = new Item(10,(DescProduct)cIt.next());
            botiga.addItem(unItem);
        }
        /*botiga.addItem(new Item(2,cataleg.GetProdFromCatalog(1)));
        botiga.addItem(new Item(4,cataleg.GetProdFromCatalog(2)));*/
        Finestra2 f2=new Finestra2(botiga);
        f2.show();
        dispose();
        setVisible(false);
    }//GEN-LAST:event_botoOKActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finestra1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LAdreça;
    private javax.swing.JLabel LDescripcio;
    private javax.swing.JLabel LNom;
    private javax.swing.JButton botoOK;
    private javax.swing.JTextField textAddress;
    private javax.swing.JTextField textNom;
    // End of variables declaration//GEN-END:variables

}
